apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "core-service.fullname" . }}
  labels:
    {{- include "core-service.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "core-service.fullname" . }}
  updatePolicy:
    updateMode: "Off"
