name: Generate chart artifact
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: echo "::set-output name=version::$(sh cmd/version.sh)" 
        id: version
      - name: Create a release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
      - name: Build chart artifact
        run: sh cmd/build.sh
      - name: Upload chart artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./core-service.tgz
          asset_name: core-service.tgz
          asset_content_type: application/tar+gzip
